task 1

WEBSITE:- books.toscrape.com

Install Required Libraries

In [1]:
!pip install requests beautifulsoup4 pandas

Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (4.13.5)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2026.5.20)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4) (2.8.4)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4) (4.15.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

Fetch the Web Page

In [2]:
import requests
from bs4 import BeautifulSoup

url = "https://books.toscrape.com/"
response = requests.get(url)
soup = BeautifulSoup(response.text, "html.parser")

Scrape Data from Multiple Pages

In [3]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

titles, prices, availability, ratings = [], [], [], []

# Loop through first 5 pages (you can extend to all 50)
for page in range(1, 6):
    url = f"http://books.toscrape.com/catalogue/page-{page}.html"
    response = requests.get(url)
    soup = BeautifulSoup(response.text, "html.parser")

    for book in soup.find_all("article", class_="product_pod"):
        titles.append(book.h3.a["title"])
        prices.append(book.find("p", class_="price_color").get_text())
        availability.append(book.find("p", class_="instock availability").get_text().strip())
        ratings.append(book.p["class"][1])

df = pd.DataFrame({
    "Title": titles,
    "Price": prices,
    "Availability": availability,
    "Rating": ratings
})
print(df.head())

                                   Title    Price Availability Rating
0                   A Light in the Attic  Â£51.77     In stock  Three
1                     Tipping the Velvet  Â£53.74     In stock    One
2                             Soumission  Â£50.10     In stock    One
3                          Sharp Objects  Â£47.82     In stock   Four
4  Sapiens: A Brief History of Humankind  Â£54.23     In stock   Five

Customize the Dataset
Convert Price to numeric values.

Map Rating words (One–Five) to numbers (1–5).

Clean Availability text.

In [5]:
# Clean price string: remove unwanted characters and convert to float
df["Price"] = df["Price"].str.replace("Â", "", regex=False)
df["Price"] = df["Price"].str.replace("£", "", regex=False)
df["Price"] = df["Price"].astype(float)

In [7]:
df

,Title,Price,Availability,Rating
0,A Light in the Attic,51.77,In stock,Three
1,Tipping the Velvet,53.74,In stock,One
2,Soumission,50.10,In stock,One
3,Sharp Objects,47.82,In stock,Four
4,Sapiens: A Brief History of Humankind,54.23,In stock,Five
...,...,...,...,...
95,Lumberjanes Vol. 3: A Terrible Plan (Lumberjan...,19.92,In stock,Two
96,"Layered: Baking, Building, and Styling Spectac...",40.11,In stock,One
97,Judo: Seven Steps to Black Belt (an Introducto...,53.90,In stock,Two
98,Join,35.67,In stock,Five
99,In the Country We Love: My Family Divided,22.00,In stock,Four

Save  Custom Dataset

In [8]:
df.to_csv("custom_books_dataset.csv", index=False)

In [9]:
df

,Title,Price,Availability,Rating
0,A Light in the Attic,51.77,In stock,Three
1,Tipping the Velvet,53.74,In stock,One
2,Soumission,50.10,In stock,One
3,Sharp Objects,47.82,In stock,Four
4,Sapiens: A Brief History of Humankind,54.23,In stock,Five
...,...,...,...,...
95,Lumberjanes Vol. 3: A Terrible Plan (Lumberjan...,19.92,In stock,Two
96,"Layered: Baking, Building, and Styling Spectac...",40.11,In stock,One
97,Judo: Seven Steps to Black Belt (an Introducto...,53.90,In stock,Two
98,Join,35.67,In stock,Five
99,In the Country We Love: My Family Divided,22.00,In stock,Four



Prices are numeric, enabling statistical analysis and visualizations.

Ratings are converted to numbers (1–5), making sentiment or quality analysis possible.

Availability is standardized, allowing stock trend analysis.